---

- name: Ensure clone of template 999
  community.general.proxmox:
    node: heidmall
    api_user: root@pam
    api_password: "{{ heimdall_root }}"
    api_host: heimdall.akuadora.net
    clone: 999
    hostname: ¨{{ newhostname }}.akuadora.internal¨

...
